# Silverblue's automatic layout: root, home and var subvolumes on zstd-compressed btrfs
[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /home (min 512 MiB, free 50 GiB)
    /var  (btrfs)
